### ISSUE TITLE
CardDetector.java line 25

### ISSUE THREAD

**Issue by mubarakansari715** [network-international/payment-sdk-android#27]
Fatal Exception: java.lang.NumberFormatException: Invalid BigInteger: 0457 4
       at java.math.BigInt.invalidBigInteger(BigInt.java:88)
       at java.math.BigInt.checkString(BigInt.java:142)
       at java.math.BigInt.putDecString(BigInt.java:92)
       at java.math.BigInteger.<init>(BigInteger.java:219)
       at payment.sdk.android.cardpayment.card.CardDetector$Companion.findMatchingCard(CardDetector.java:25)
       at payment.sdk.android.cardpayment.card.CardDetector$Companion.<init>(CardDetector.java:20)
       at payment.sdk.android.cardpayment.card.CardDetector.detect(CardDetector.java:17)
       at payment.sdk.android.cardpayment.CardPaymentPresenter.onCardNumberChanged(CardPaymentPresenter.java:93)
       at payment.sdk.android.cardpayment.CardPaymentView.onTextChangeListener(CardPaymentView.java:188)
       at payment.sdk.android.cardpayment.widget.NumericMaskedEditText.onNewText(NumericMaskedEditText.java:108)
       at payment.sdk.android.cardpayment.widget.NumericMaskInputFilter.filter(NumericMaskInputFilter.java:78)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:517)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:393)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by mu1ex** [comment]
Looks like a stale issue and not reproducible. Please reopen this issue if you're still facing it
