### ISSUE TITLE
SdkComponent.java line 74

### ISSUE THREAD

**Issue by mubarakansari715** [network-international/payment-sdk-android#30]
com.paypal.pyplcheckout.di.SdkComponent$Companion.getInstance

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.***.app/com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity}: java.lang.IllegalStateException: Required value was null.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by mubarakansari715** [comment]
> com.paypal.pyplcheckout.di.SdkComponent$Companion.getInstance
> 
> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.***.app/com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity}: java.lang.IllegalStateException: Required value was null. at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7839) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
