### ISSUE TITLE
ThreeDSecureTwoActivity.java line 66

### ISSUE THREAD

**Issue by mubarakansari715** [network-international/payment-sdk-android#34]
hello @mu1ex 
Hope you are doing well,

Here I'm facing one issue. Kindly suggest and do needful.
Android version: 12

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alokozayshop.app/payment.sdk.android.cardpayment.threedsecuretwo.ThreeDSecureTwoActivity}: java.lang.IllegalStateException: You need to use a **Theme.AppCompat theme** (or descendant) with this activity.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by ShivaniChandel** [comment]
hello @mu1ex
I'm facing a similar issue. Kindly suggest and do needful.

\payment-sdk-android-master\payment-sdk-android-master\payment-sdk\src\main\java\payment\sdk\android\cardpayment\threedsecuretwo\ThreeDSecureTwoActivity.kt: (15, 12): Unresolved reference: usdk
Downloads\payment-sdk-android-master\payment-sdk-android-master\payment-sdk\src\main\java\payment\sdk\android\cardpayment\threedsecuretwo\ThreeDSecureTwoActivity.kt: (16, 12): Unresolved reference: emvco
Downloads\payment-sdk-android-master\payment-sdk-android-master\payment-sdk\src\main\java\payment\sdk\android\cardpayment\threedsecuretwo\ThreeDSecureTwoActivity.kt: (17, 12): Unresolved reference: emvco

no library found

**Comment by mu1ex** [comment]
These issues are fixed in the latest version of SDK. Please update and reopen if issue still persists.
