### ISSUE TITLE
App Crash or Exception On CardPaymentActivity.kt

### ISSUE THREAD

**Issue by HRN8891** [network-international/payment-sdk-android#40]
Hello Team,

We are using NISDK in our application and we have identified the crash from the log for the specific activity which is mentioned here.

CardPaymentActivity.kt line 2 in payment.sdk.android.cardpayment.CardPaymentActivity.onActivityResult

We have also attached the image of stack trace report.
Please check and Let us know.

  
![Screenshot 2023-04-14 at 3 09 28 PM](https://user-images.githubusercontent.com/38550371/232010392-39d38e94-8b81-4edb-bfd2-922409c5101d.png)

**Comment by ladroshan** [comment]
Getting error using NISDK  


Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=110, result=-1, data=Intent { (has extras) }} to activity {com.testApp/payment.sdk.android.cardpayment.CardPaymentActivity}: kotlin.KotlinNullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5994)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:6033)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
